version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: quizdb
    ports:
      - '3001:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
